dist: focal
language: python
python:
  - "3.9"   # Travis default je starý 3.7, proto radši 3.9

services:
  - docker

env:
  global:
    - APP_IMAGE=keboola-component

before_install:
  # Upgrade pipu, setuptools a wheel, aby zvládly instalaci z GitHubu
  - python3 -m pip install --upgrade pip setuptools wheel

before_script:
  # Build Docker image
  - docker build . --tag=$APP_IMAGE

script:
  - docker images

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    tags: true
