sudo: required
language: bash
services:
  - docker

before_script:
  - export APP_IMAGE=keboola-component
  - docker build . --tag=$APP_IMAGE

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: |
    echo "--- Debugging deploy.sh ---"
    # Přidání cesty pro Ruby gems do PATH
    export PATH="$HOME/bin:$HOME/perl5/perlbrew/bin:$HOME/.rvm/bin:$PATH"
    export PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH" || { echo "Failed to add Ruby gem path to PATH."; exit 1; }
    echo "Current PATH: $PATH"
    
    # Ověření, zda je kbc-developer-portal nyní dostupný
    which kbc-developer-portal || { echo "Error: kbc-developer-portal command not found after PATH update."; exit 1; }
    
    chmod +x ./deploy.sh
    bash -e -x ./deploy.sh
    echo "--- Debugging deploy.sh Finished ---"
  on:
    tags: true
