sudo: false
services:
  - docker

before_script:
  - export APP_IMAGE=keboola-component
  - docker build -t $APP_IMAGE .
  # případně testování:
  # - docker run $APP_IMAGE flake8
  # - docker run $APP_IMAGE python -m unittest discover

script:
  - echo "✅ Build OK"

deploy:
  provider: script
  skip_cleanup: true
  script: bash -x ./deploy.sh
  on:
    tags: true
